### ISSUE TITLE
Unsafe assignment of `any` value

### ISSUE THREAD

**Issue by grantvine-sc** [JamesRobertWiseman/zaid-ts#1]
I appear to get an issue in a create-t3-app configuration (out of box) with this library, issue is as follows:

![image](https://github.com/JamesRobertWiseman/zaid-ts/assets/121936135/afa7f94a-38ce-4342-b749-d58213002c2f)

```code
Unsafe assignment of an `any` value.eslint[@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment)
Unsafe call of an `any` typed value.eslint[@typescript-eslint/no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call)
```

I have managed to resolve the error by adjusting my import statement to:

import { isValid as isZAIDNumber } from "zaid-ts/dist/index";

If anyone else has similar issues, possibly an adjustment to package exports is what fixes this properly but I don't have that answer offhand ;)

**Comment by JamesRobertWiseman** [comment]
Can you share your code that is using this?
